type Comment {
    id: ID!
    text: String!
    author: User!
}

type Post {
    id: ID!
    title: String!
    body: String!
    published: Boolean!
    author: User!
}

type Query {
    comments: [Comment!]!
    me: User!
    post: Post!
    posts(query: String): [Post!]!
    users(query: String): [User!]!
}

type User {
    id: ID!
    name: String!
    email: String!
    age: Int
    posts: [Post!]!
    comments: [Comment!]!
}
